# Generated by Django 5.2.6 on 2025-09-27 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pscds_priorities',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('import_field', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('default_priority_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pscds_projects',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pscds_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshots_active', models.IntegerField(default=0)),
                ('manual_time', models.IntegerField(default=0)),
                ('computer_time_popup', models.IntegerField(default=0)),
                ('blur_screenshots', models.IntegerField(default=0)),
                ('web_and_app_monitoring', models.BooleanField(default=False)),
                ('screenshots_interval', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('important', models.BooleanField(default=False)),
                ('change_password', models.BooleanField(default=False)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('user_language', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('nonce', models.IntegerField(blank=True, null=True)),
                ('client_installed', models.BooleanField(default=False)),
                ('permanent_screenshots', models.BooleanField(default=False)),
                ('last_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('remember_me_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('remember_me_token', models.CharField(blank=True, max_length=255, null=True)),
                ('datebirth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pscds_users',
            },
        ),
        migrations.CreateModel(
            name='WarningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pscds_warning_reports',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('work_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warning_time', models.FloatField(default=0)),
                ('assigned_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('status_id', models.IntegerField(default=0)),
                ('relative_position', models.DecimalField(decimal_places=30, default=0, max_digits=64)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pscds.priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pscds.project')),
            ],
            options={
                'db_table': 'pscds_tasks',
            },
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('different_timezone', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('activity_fill', models.IntegerField(default=0)),
                ('mouse_fill', models.IntegerField(default=0)),
                ('keyboard_fill', models.IntegerField(default=0)),
                ('job', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_intervals', to='pscds.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.user')),
            ],
            options={
                'db_table': 'pscds_time_intervals',
            },
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.user')),
            ],
            options={
                'db_table': 'pscds_tasks_users',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(through='pscds.TaskUser', to='pscds.user'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.user')),
            ],
            options={
                'db_table': 'pscds_requests',
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.user')),
            ],
            options={
                'db_table': 'pscds_projects_users',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('type', models.IntegerField()),
                ('message', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('ready', 'Ready')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.user')),
            ],
            options={
                'db_table': 'pscds_notifications',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('event', models.TextField()),
                ('sit', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('os', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pscds.user')),
            ],
            options={
                'db_table': 'pscds_logs',
            },
        ),
    ]
