# Generated by Django 5.2.1 on 2025-05-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "ADMIN"), ("USER", "USER")], default="USER"
            ),
        ),
    ]
