# Generated by Django 5.2.1 on 2025-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "SUPER_ADMIN"),
                    ("ADMIN", "ADMIN"),
                    ("USER", "USER"),
                ],
                default="USER",
            ),
        ),
    ]
