# Generated by Django 5.2.1 on 2025-06-07 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_full_name_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
