# Generated by Django 5.2.1 on 2025-06-25 04:49

from django.db import migrations


def update_full_name(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        if not user.full_name:
            user.full_name = f"{user.first_name} {user.last_name}"
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.RunPython(update_full_name),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
