# Generated by Django 5.2.1 on 2025-08-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_user_first_name_remove_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
