# Generated by Django 5.2.1 on 2025-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
