# Generated by Django 5.2.1 on 2025-08-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20250805_0759"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporttime",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reporttime",
            name="updated_at",
        ),
    ]
