# Generated by Django 6.0.2 on 2026-03-07 10:34

from django.db import migrations, models


def seed_admin_permissions(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="ADMIN").update(
        admin_permissions={
            "manage_bookings": True,
            "manage_tables": True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_reporttime_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_admin_permissions, migrations.RunPython.noop),
    ]
