# Generated by Django 6.0.2 on 2026-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_admin_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('WAITER', 'WAITER'), ('CASHIER', 'CASHIER'), ('USER', 'USER')], default='USER'),
        ),
    ]
