# Generated by Django 5.2.6 on 2025-10-08 03:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Đã xóa", verbose_name="Đã xóa"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("INDOOR", "Indoor"),
                            ("OUTDOOR", "Outdoor"),
                            ("PRIVATE", "Private Dining"),
                            ("BAR", "Bar Seating"),
                            ("BOOTH", "Booth"),
                            ("WINDOW", "Window Seating"),
                        ],
                        default="INDOOR",
                        max_length=20,
                        verbose_name="Table Type",
                    ),
                ),
                ("floor", models.PositiveIntegerField(default=1, verbose_name="Floor")),
                (
                    "section",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Section"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved"),
                            ("MAINTENANCE", "Under Maintenance"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Width (meters)",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Length (meters)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "db_table": "restaurant_tables",
                "ordering": ["floor", "id"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Đã xóa", verbose_name="Đã xóa"
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Guest Name"
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Guest Email",
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Guest Phone"
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="Booking Date")),
                ("booking_time", models.TimeField(verbose_name="Booking Time")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=2.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(8.0),
                        ],
                        verbose_name="Duration (Hours)",
                    ),
                ),
                (
                    "party_size",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Party Size",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website"),
                            ("PHONE", "Phone"),
                            ("WALK_IN", "Walk-in"),
                            ("MOBILE_APP", "Mobile App"),
                            ("THIRD_PARTY", "Third Party"),
                        ],
                        default="WEBSITE",
                        max_length=20,
                        verbose_name="Booking Source",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True, null=True, verbose_name="Special Requests"
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dietary Restrictions"
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Occasion"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Contact Phone"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Confirmation Code",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Internal Notes"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Cancellation Reason"
                    ),
                ),
                (
                    "send_sms_reminder",
                    models.BooleanField(default=True, verbose_name="Send SMS Reminder"),
                ),
                (
                    "send_email_reminder",
                    models.BooleanField(
                        default=True, verbose_name="Send Email Reminder"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelled By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="restaurant_booking.table",
                        verbose_name="Table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "restaurant_bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["table", "booking_date", "booking_time"],
                        name="restaurant__table_i_bdb496_idx",
                    ),
                    models.Index(
                        fields=["customer", "booking_date"],
                        name="restaurant__custome_32f966_idx",
                    ),
                    models.Index(
                        fields=["status", "booking_date"],
                        name="restaurant__status_2e4cff_idx",
                    ),
                ],
            },
        ),
    ]
