# Generated by Django 5.2.6 on 2025-10-10 03:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="code",
            field=models.CharField(
                default="93C2E0K3",
                max_length=20,
                unique=True,
                verbose_name="Mã đặt bàn",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(verbose_name="Ngày đặt bàn"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.TimeField(verbose_name="Giờ đặt bàn"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Lý do hủy"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian hủy"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người hủy",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian hoàn thành"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="confirmation_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Mã xác nhận",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian xác nhận"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="contact_email",
            field=models.EmailField(max_length=254, verbose_name="Email liên hệ"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="contact_phone",
            field=models.CharField(max_length=20, verbose_name="Số điện thoại liên hệ"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="dietary_restrictions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hạn chế ăn uống"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=2.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(8.0),
                ],
                verbose_name="Thời gian (giờ)",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email khách"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tên khách"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Số điện thoại khách"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ghi chú nội bộ"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="occasion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dịp đặc biệt"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="party_size",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Số người",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="send_email_reminder",
            field=models.BooleanField(default=True, verbose_name="Gửi nhắc nhở email"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="send_sms_reminder",
            field=models.BooleanField(default=True, verbose_name="Gửi nhắc nhở SMS"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("WEBSITE", "Website"),
                    ("PHONE", "Điện thoại"),
                    ("WALK_IN", "Đến trực tiếp"),
                    ("MOBILE_APP", "Ứng dụng di động"),
                    ("THIRD_PARTY", "Bên thứ ba"),
                ],
                default="WEBSITE",
                max_length=20,
                verbose_name="Nguồn đặt bàn",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(
                blank=True, null=True, verbose_name="Yêu cầu đặc biệt"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xác nhận"),
                    ("CONFIRMED", "Đã xác nhận"),
                    ("CANCELLED", "Đã hủy"),
                    ("COMPLETED", "Hoàn thành"),
                    ("NO_SHOW", "Không đến"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="restaurant_booking.table",
                verbose_name="Bàn",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Sức chứa",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="floor",
            field=models.PositiveIntegerField(default=1, verbose_name="Tầng"),
        ),
        migrations.AlterField(
            model_name="table",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Chiều dài (mét)",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="table",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAIN_DINING", "Khu vực chính"),
                    ("WINDOW_SEATING", "Khu vực cửa sổ"),
                    ("BAR_AREA", "Khu vực quầy bar"),
                    ("OUTDOOR_PATIO", "Khu vực ngoài trời"),
                    ("PRIVATE_DINING", "Khu vực phòng riêng"),
                    ("BOOTH_AREA", "Khu vực ghế ngồi"),
                ],
                max_length=50,
                null=True,
                verbose_name="Khu vực",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Có sẵn"),
                    ("OCCUPIED", "Đang sử dụng"),
                    ("RESERVED", "Đã đặt"),
                    ("MAINTENANCE", "Bảo trì"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_type",
            field=models.CharField(
                choices=[
                    ("INDOOR", "Trong nhà"),
                    ("OUTDOOR", "Ngoài trời"),
                    ("PRIVATE", "Phòng riêng"),
                    ("BAR", "Quầy bar"),
                    ("BOOTH", "Ghế ngồi"),
                    ("WINDOW", "Cửa sổ"),
                ],
                default="INDOOR",
                max_length=20,
                verbose_name="Loại bàn",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Chiều rộng (mét)",
            ),
        ),
    ]
