# Generated by Django 5.2.6 on 2025-10-10 03:15

from django.db import migrations

def create_sample_tables(apps, schema_editor):
    Table = apps.get_model('restaurant_booking', 'Table')

    Table.objects.all().delete()
    
    # Sample tables for the restaurant
    tables_data = [
        # Ground Floor - Main Dining Area
        {'table_type': 'INDOOR', 'capacity': 2, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 2, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 4, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 4, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 6, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 6, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 8, 'floor': 1, 'section': 'MAIN_DINING'},

        # Ground Floor - Window Seating
        {'table_type': 'WINDOW', 'capacity': 2, 'floor': 1, 'section': 'WINDOW_SEATING'},
        {'table_type': 'WINDOW', 'capacity': 2, 'floor': 1, 'section': 'WINDOW_SEATING'},
        {'table_type': 'WINDOW', 'capacity': 4, 'floor': 1, 'section': 'WINDOW_SEATING'},
        {'table_type': 'WINDOW', 'capacity': 4, 'floor': 1, 'section': 'WINDOW_SEATING'},

        # Ground Floor - Bar Area
        {'table_type': 'BAR', 'capacity': 2, 'floor': 1, 'section': 'BAR_AREA'},
        {'table_type': 'BAR', 'capacity': 2, 'floor': 1, 'section': 'BAR_AREA'},
        {'table_type': 'BAR', 'capacity': 4, 'floor': 1, 'section': 'BAR_AREA'},

        # Ground Floor - Outdoor Patio
        {'table_type': 'OUTDOOR', 'capacity': 2, 'floor': 1, 'section': 'OUTDOOR_PATIO'},
        {'table_type': 'OUTDOOR', 'capacity': 2, 'floor': 1, 'section': 'OUTDOOR_PATIO'},
        {'table_type': 'OUTDOOR', 'capacity': 4, 'floor': 1, 'section': 'OUTDOOR_PATIO'},
        {'table_type': 'OUTDOOR', 'capacity': 4, 'floor': 1, 'section': 'OUTDOOR_PATIO'},
        {'table_type': 'OUTDOOR', 'capacity': 6, 'floor': 1, 'section': 'OUTDOOR_PATIO'},

        # First Floor - Private Dining
        {'table_type': 'PRIVATE', 'capacity': 8, 'floor': 2, 'section': 'PRIVATE_DINING'},
        {'table_type': 'PRIVATE', 'capacity': 10, 'floor': 2, 'section': 'PRIVATE_DINING'},
        {'table_type': 'PRIVATE', 'capacity': 12, 'floor': 2, 'section': 'PRIVATE_DINING'},
        {'table_type': 'PRIVATE', 'capacity': 16, 'floor': 2, 'section': 'PRIVATE_DINING'},

        # First Floor - Booths
        {'table_type': 'BOOTH', 'capacity': 4, 'floor': 2, 'section': 'BOOTH_AREA'},
        {'table_type': 'BOOTH', 'capacity': 4, 'floor': 2, 'section': 'BOOTH_AREA'},
        {'table_type': 'BOOTH', 'capacity': 6, 'floor': 2, 'section': 'BOOTH_AREA'},
        {'table_type': 'BOOTH', 'capacity': 6, 'floor': 2, 'section': 'BOOTH_AREA'},

        # First Floor - Regular Dining
        {'table_type': 'INDOOR', 'capacity': 2, 'floor': 2, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 2, 'floor': 2, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 4, 'floor': 2, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 4, 'floor': 2, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 6, 'floor': 2, 'section': 'MAIN_DINING'},

        # Wheelchair Accessible Tables (using existing section names)
        {'table_type': 'INDOOR', 'capacity': 4, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'INDOOR', 'capacity': 2, 'floor': 1, 'section': 'MAIN_DINING'},
        {'table_type': 'OUTDOOR', 'capacity': 4, 'floor': 1, 'section': 'OUTDOOR_PATIO'},
    ]

    for table_data in tables_data:
        Table.objects.create(**table_data)


def reverse_create_sample_tables(apps, schema_editor):
    Table = apps.get_model('restaurant_booking', 'Table')
    Table.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_booking", "0002_booking_code_alter_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.RunPython(create_sample_tables, reverse_create_sample_tables),
    ]
