# Generated by Django 5.2.6 on 2025-10-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_booking", "0003_auto_20251010_0315"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="restaurant__custome_32f966_idx",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="cancelled_by",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="confirmation_code",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="dietary_restrictions",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="occasion",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="send_email_reminder",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="send_sms_reminder",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="special_requests",
        ),
        migrations.RemoveField(
            model_name="table",
            name="section",
        ),
        migrations.AlterField(
            model_name="booking",
            name="code",
            field=models.CharField(
                default="VD2SMYCV",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Mã đặt bàn",
            ),
        ),
    ]
