# Generated by Django 5.2.6 on 2025-10-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant_booking",
            "0004_remove_booking_restaurant__custome_32f966_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="restaurant__table_i_bdb496_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="restaurant__status_2e4cff_idx",
        ),
        migrations.AlterField(
            model_name="booking",
            name="code",
            field=models.CharField(
                default="7DZXDPA4",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Mã đặt bàn",
            ),
        ),
    ]
