# Generated by Django 6.0.2 on 2026-03-07 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import restaurant_booking.models.booking


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0005_remove_booking_restaurant__table_i_bdb496_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác nhận'),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default=restaurant_booking.models.booking.generate_booking_code, editable=False, max_length=20, unique=True, verbose_name='Mã đặt bàn'),
        ),
    ]
