# Generated by Django 6.0.2 on 2026-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0007_menucategory_restaurantprofile_menuitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='default_image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả ảnh mặc định'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='default_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ảnh mặc định'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dietary_labels',
            field=models.JSONField(blank=True, default=list, verbose_name='Nhãn ăn kiêng'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả ảnh'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ảnh món'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='Bán chạy'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_illustration',
            field=models.BooleanField(default=False, verbose_name='Ảnh minh họa'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_kid_friendly',
            field=models.BooleanField(default=False, verbose_name='Phù hợp trẻ em'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='serving_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bán đến'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='serving_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bán từ'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spicy_level',
            field=models.CharField(choices=[('NONE', 'Không cay'), ('MILD', 'Ít cay'), ('MEDIUM', 'Cay vừa'), ('HOT', 'Cay nhiều')], default='NONE', max_length=16, verbose_name='Mức độ cay'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='suggested_pairings',
            field=models.ManyToManyField(blank=True, related_name='paired_from', to='restaurant_booking.menuitem', verbose_name='Món gợi ý ăn kèm'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tag món ăn'),
        ),
    ]
