# Generated by Django 6.0.2 on 2026-06-29 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0011_alter_booking_status_payment_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True, verbose_name='Mã phiên chat')),
                ('mode', models.CharField(choices=[('SALES', 'Tư vấn / menu'), ('BOOKING', 'Đặt bàn')], default='SALES', max_length=16, verbose_name='Chế độ hội thoại')),
                ('stage', models.CharField(choices=[('NONE', 'Chưa vào booking'), ('COLLECT_DATETIME', 'Hỏi ngày giờ'), ('COLLECT_PARTY_SIZE', 'Hỏi số người'), ('COLLECT_SEATING', 'Hỏi khu vực / tầng'), ('SELECT_TABLE', 'Chọn bàn'), ('DEPOSIT_NOTICE', 'Thông báo đặt cọc'), ('COLLECT_CONTACT', 'Hỏi thông tin liên hệ'), ('CONFIRM', 'Chờ xác nhận'), ('DONE', 'Đã hoàn tất')], default='NONE', max_length=32, verbose_name='Bước trong luồng đặt bàn')),
                ('slots', models.JSONField(blank=True, default=dict, verbose_name='Thông tin đặt bàn đã thu thập')),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tên khách')),
                ('selected_item_ids', models.JSONField(blank=True, default=list, verbose_name='Món khách đã chọn trước')),
                ('last_table_options', models.JSONField(blank=True, default=list, verbose_name='Danh sách bàn trống đã gợi ý gần nhất')),
                ('booking_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã đặt bàn đã tạo')),
            ],
            options={
                'verbose_name': 'Chat session',
                'verbose_name_plural': 'Chat sessions',
                'db_table': 'restaurant_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
