# Generated by Django 6.0.2 on 2026-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0012_chatsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='stage',
            field=models.CharField(choices=[('NONE', 'Chưa vào booking'), ('COLLECT_NAME', 'Hỏi tên'), ('COLLECT_DATETIME', 'Hỏi ngày giờ'), ('COLLECT_PARTY_SIZE', 'Hỏi số người'), ('COLLECT_SEATING', 'Hỏi khu vực / tầng'), ('SELECT_TABLE', 'Chọn bàn'), ('DEPOSIT_NOTICE', 'Thông báo đặt cọc'), ('COLLECT_CONTACT', 'Hỏi thông tin liên hệ'), ('CONFIRM', 'Chờ xác nhận'), ('DONE', 'Đã hoàn tất')], default='NONE', max_length=32, verbose_name='Bước trong luồng đặt bàn'),
        ),
    ]
