# Generated by Django 6.0.2 on 2026-06-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0013_alter_chatsession_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='order_closed',
            field=models.BooleanField(default=False, verbose_name='Khách đã chốt món'),
        ),
    ]
