# Generated by Django 5.2.1 on 2025-07-31 08:54

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(null=True)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(null=True)),
            ],
        ),
    ]
