# Generated by Django 5.2.1 on 2025-07-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Document",
            new_name="DocumentEmbedding",
        ),
    ]
