# Generated by Django 5.2.6 on 2025-09-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_service", "0004_alter_message_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="html_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
