# Generated by Django 5.2.6 on 2025-10-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_service", "0005_message_html_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="html_message",
        ),
        migrations.AddField(
            model_name="message",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
