"""
Django settings for PSCD Assistant project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE = os.getenv("USE_ENV_FILE", ".env")

if ENV_FILE and len(ENV_FILE) > 0:
    # Let real environment variables win so Docker can override .env values cleanly.
    load_dotenv(os.path.join(BASE_DIR, ENV_FILE), verbose=True, override=False)
else:
    load_dotenv(verbose=True, override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("APPLICATION_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "corsheaders",
    "django_filters",
    #
    "common",
    "accounts",
    "restaurant_booking",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "common.utils.middleware.CorrelationMiddleware",
]

ROOT_URLCONF = "api_chat_bot.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api_chat_bot.wsgi.application"
ASGI_APPLICATION = "api_chat_bot.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# ---------------------------------------------------------------------------- #
#                                 Media file                                   #
# ---------------------------------------------------------------------------- #
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S.%f%z",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "common.custom.pagination.CustomPagination",
    "UNAUTHENTICATED_USER": None,
    "PAGE_SIZE": 50,
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser"],
    "DEFAULT_SCHEMA_CLASS": "common.swaggers.custom.CustomAutoSchema",
    "EXCEPTION_HANDLER": "common.custom.exceptions.custom_exception_handler",
    # Throllers settings
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_RATES_ANON"),
        "user": os.getenv("THROTTLE_RATES_USER"),
    },
    "COERCE_DECIMAL_TO_STRING": False,
}

AUTH_USER_MODEL = "accounts.User"

AUTH_HEADER_TYPES = ("Bearer",)
ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:3000",
    "http://localhost:4200",
    "http://localhost:5173",
    *(filter(lambda x: len(x) > 0, os.getenv("CORS_ALLOWED_ORIGINS", "").split(","))),
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:3000",
    "http://localhost:4200",
    "http://localhost:5173",
    *(filter(lambda x: len(x) > 0, os.getenv("CSRF_TRUSTED_ORIGINS", "").split(","))),
]
CORS_ALLOW_HEADERS = list(default_headers) + [
    "X-Auth-User",
]

SECURE_PROXY_SSL_HEADER = ["HTTP_X_FORWARDED_PROTO", "https"]

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=int(os.getenv("ACCESS_TOKEN_LIFETIME"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=int(os.getenv("REFRESH_TOKEN_LIFETIME"))),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": AUTH_HEADER_TYPES,
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
]

AUTHENTICATION_BACKENDS = [
    "common.custom.backend.RoleBasedAdminBackend",
]

X_FRAME_OPTIONS = "SAMEORIGIN"
XS_SHARING_ALLOWED_METHODS = ["POST", "GET", "OPTIONS", "PUT", "DELETE"]

# ---------------------------------------------------------------------------- #
#                                    WEBSITE                                   #
# ---------------------------------------------------------------------------- #
WEBSITE_NAME = os.getenv("WEBSITE_NAME")
WEBSITE_URL = os.getenv("WEBSITE_URL")
BACKEND_URL = os.getenv("BACKEND_URL")

# ---------------------------------------------------------------------------- #
#                                    LOGS                                      #
# ---------------------------------------------------------------------------- #
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "req_uuid": {"()": "common.utils.middleware.RequestUuidFilter"},
        "req_ip": {"()": "common.utils.middleware.RequestIPFilter"},
    },
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] [%(req_uuid)s] [%(req_ip)s] %(levelname)-8s %(message)s"
        },
        "batch": {
            "format": "[%(asctime)s] [%(req_uuid)s] [%(req_ip)s] %(levelname)-8s %(message)s"
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "filters": ["req_uuid", "req_ip"],
            "formatter": "standard",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "ERROR", "propagate": True},
        "apscheduler": {"handlers": ["console"], "level": "ERROR", "propagate": True},
        "": {
            "handlers": ["console"],
            # "level": "DEBUG" if DEBUG else "INFO",
            "level": "INFO",
            "propagate": True,
        },
    },
}


# ---------------------------------------------------------------------------- #
#                                 SWAGGER                                      #
# ---------------------------------------------------------------------------- #
DISPLAY_SWAGGER = int(os.getenv("IS_DISPLAY_SWAGGER", "0"))

SPECTACULAR_SETTINGS = {
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api",
    "TITLE": "PSCD Assistant API Documentation",
    "DESCRIPTION": "PSCD Assistant API Documentation",
}

# ---------------------------------------------------------------------------- #
#                                    AUTH                                      #
# ---------------------------------------------------------------------------- #
USER_RESET_PASSWORD_CALLBACK_URL = os.getenv("USER_RESET_PASSWORD_CALLBACK_URL")
USER_VERIFY_EMAIL_CALLBACK_URL = os.getenv("USER_VERIFY_EMAIL_CALLBACK_URL")
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT"))
EMAIL_CRYPTER_FIELD_KEY = os.getenv("EMAIL_CRYPTER_FIELD_KEY")


# ---------------------------------------------------------------------------- #
#                                 Google                                       #
# ---------------------------------------------------------------------------- #
GOOGLE_OAUTH2_CLIENT_ID = os.getenv("GOOGLE_OAUTH2_CLIENT_ID")
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH2_CLIENT_SECRET")
GOOGLE_OAUTH2_USER_INFO_URL = os.getenv("GOOGLE_OAUTH2_USER_INFO_URL")

# Google Sheets configuration
GOOGLE_SHEETS_SPREADSHEET_ID = os.getenv("GOOGLE_SHEETS_SPREADSHEET_ID")
GOOGLE_SHEETS_WORKSHEET_NAME = os.getenv("GOOGLE_SHEETS_WORKSHEET_NAME", "Orders")

# Google Service Account credentials (for Google Sheets API)
GOOGLE_SERVICE_ACCOUNT = {
    'type': os.getenv("GOOGLE_SERVICE_ACCOUNT_TYPE"),
    'project_id': os.getenv("GOOGLE_SERVICE_ACCOUNT_PROJECT_ID"),
    'private_key_id': os.getenv("GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID"),
    'private_key': os.getenv("GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY"),
    'client_email': os.getenv("GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL"),
    'client_id': os.getenv("GOOGLE_SERVICE_ACCOUNT_CLIENT_ID"),
    'auth_uri': os.getenv("GOOGLE_SERVICE_ACCOUNT_AUTH_URI", "https://accounts.google.com/o/oauth2/auth"),
    'token_uri': os.getenv("GOOGLE_SERVICE_ACCOUNT_TOKEN_URI", "https://oauth2.googleapis.com/token"),
    'auth_provider_x509_cert_url': os.getenv("GOOGLE_SERVICE_ACCOUNT_AUTH_PROVIDER_CERT_URL", "https://www.googleapis.com/oauth2/v1/certs"),
    'client_x509_cert_url': os.getenv("GOOGLE_SERVICE_ACCOUNT_CLIENT_CERT_URL"),
    'universe_domain': os.getenv("GOOGLE_SERVICE_ACCOUNT_UNIVERSE_DOMAIN", "googleapis.com")
}

# ---------------------------------------------------------------------------- #
#                                 MAIL                                         #
# ---------------------------------------------------------------------------- #
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST") or os.getenv("SMTP_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT") or os.getenv("SMTP_PORT") or 587)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER") or os.getenv("SMTP_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD") or os.getenv("SMTP_PASSWORD")
EMAIL_USE_TLS = (
    str(os.getenv("EMAIL_USE_TLS") or os.getenv("SMTP_USE_TLS") or "true").lower()
    in ["1", "true", "yes", "on"]
)
DEFAULT_FROM_EMAIL = (
    os.getenv("DEFAULT_FROM_EMAIL")
    or os.getenv("SMTP_FROM")
    or f"PSCD Japanese Dining <{EMAIL_HOST_USER}>"
)

# ---------------------------------------------------------------------------- #
#                                 AWS                                          #
# ---------------------------------------------------------------------------- #
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION")

# ---------------------------------------------------------------------------- #
#                                 S3 Storage                                   #
# ---------------------------------------------------------------------------- #
AWS_ACCESS_KEY_ID = os.getenv("AWS_S3_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_S3_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION")
AWS_S3_CUSTOM_DOMAIN = "%s.s3.amazonaws.com" % AWS_STORAGE_BUCKET_NAME
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = "public-read"


# ---------------------------------------------------------------------------- #
#                                 OPENAI                                       #
# ---------------------------------------------------------------------------- #
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
